name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Files
        uses: actions/checkout@v1
      - name: Run Tests and Build
        run: docker build -t myimage . && docker create -ti --name builder myimage bash && docker cp builder:/usr/local/bin/monitor /usr/local/bin/monitor && docker rm -f builder 
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: monitor
            path: /usr/local/bin/monitor
            retention-days: 10